### ISSUE TITLE
Change the formatting and parsing of all date fields on the site.

### ISSUE THREAD

**Issue by RWalport** [sharewave/frontus#96] opened 2014-04-29 17:24 UTC
Currently they only take 4

**Comment by r0ml** [comment] 2015-01-23 22:36
Change all date input fields across the entire site to take 2 or 4 digit years.  Change all date displays to use a locale which allows 2 or 4 digit years -- as well as localization formatting

**Comment by r0ml** [comment] 2015-01-23 22:40
Duplicate of #364

**Comment by r0ml** [comment] 2015-01-23 22:57
Consolidated into #1506

**Closed by r0ml** 2015-01-23 22:57 UTC
Labels: enhancement
