### ISSUE TITLE
company plan changer formatting

### ISSUE THREAD

**Issue by alanmcgee** [sharewave/frontus#1381] opened 2015-01-15 18:45 UTC
these are out of order, and other obvious style fixes...

![screen shot 2015-01-15 at 1 44 31 pm](https://cloud.githubusercontent.com/assets/2709177/5763980/b4c82cda-9cbc-11e4-9f02-2cb3076f1c30.png)

**Comment by BertHartm** [comment] 2015-01-15 18:57
Duplicate of #1376

**Closed by BertHartm** 2015-01-15 18:57 UTC
Labels: UX
